dist: trusty
sudo: required
addons:
  sonarcloud:
    organization: alexindigo-github
    branches:
      - sonarcloud
      - master
    token: $SONAR_TOKEN
jdk:
  - oraclejdk8
script:
  - sonar-scanner -X
cache:
  directories:
    - $HOME/.sonar/cache
