dist: trusty
sudo: required
addons:
  sonarcloud:
    organization: alexindigo-github
    token:
      - secure: >-
          WdnQ0M9qGib87hs0zy0ThFkNXhdw5uvkEtcO70qi1pUa6Z03srAmLVf5yJiQeNjqBPYVgLlOO35wIQLX1htJLaNjjkbsK8UjU7j9Zhwg5wisSqpdiVW1dBj+h73hu9xezMLk2DXK/b/hayuQVwG9FAQHKNftRL05NOsdcVPO+56mBMszj1y+NMMErofe0u4u+Lu9JPBx89RoBWJ0xZK1TIcv2My//4wvgKefM5N4qBlYtD6+0tCBb4WzE0r/W5agHebgrfGhZQW7/TWy6kep/Rtf8WZCfLogJsQHrkiWvRCjZ6FcT+6niH/mkBrGNeVcycrE/wAQu+xk3VorG79PwH6DBoTUmdfN7LoX0mox4aUyV5EroDrcAVXR0mCY0EFt6/NMSZM7RjHdWr5OBX/Un1k7ingvb8CJs/fPLQ6JVK/KAXkCRmK/fPn5lC4kZ/mKhcB8DZEaA/fLnDpJD/oSHr6JZSXiZ1TkMbYpTIyd7mHVL2Q9tF6BIhUM45CWr8/3EG8Y6Tx0bev/ElBMIhfSb2jsJWno3Px7VH1Tz6/UxzsryIcyuPwi8NEHqVlMG23JbQOCUabESbf5kv+f51bSmcyuPgDcPSMgZR4iYRTHJ+YAGwv+BVxheWCC7HRCDAvSjTVlbKLr2z8q95BnuGpaarn7I2VwvwsQ7dif020ncH4=
 jdk:
  - oraclejdk8
script:
  - sonar-scanner
cache:
  directories:
    - $HOME/.sonar/cache
